# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist_app', '0002_auto_20160309_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='craigslist_app.Category'),
            preserve_default=False,
        ),
    ]
