# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist_app', '0006_auto_20160310_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='city',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='craigslist_app.City'),
            preserve_default=False,
        ),
    ]
