# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist_app', '0007_auto_20160310_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
