# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist_app', '0008_post_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time_posted']},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='preferred_city',
        ),
    ]
